import matplotlib.pyplot as plt
text = "PB GHDU P, WKDQN BRX IRU OHWWLQJ PH NQRZ DERXW WV RIIHU WR MRLQ ZLWK XV LQ WKH JUHDW PDWWHU. ZKLOH L VWLOO KDYH PDQB LGHDV IRU KRZ WR SURVHFXWH RXU SODQ, PB GDBV DUH JURZLQJ VKRUW, DV DUH BRXUV, DQG ZH ZLOO QHHG WR ILQG RWKHUV RI D VLPLODU PLQG ZKR KDYH WKH ZLW DQG LPDJLQDWLRQ WR FDUUB LW IRUZDUG. RXU DELOLWB WR LQIOXHQFH PDWWHUV GLUHFWOB ZLOO FRQWLQXH WR GHSHQG RQ WKH SRZHU RI WKH GHYLFHV ZH FDQ IDVKLRQ, DQG LW ZLOO EH FOHDU WR BRX WKDW WKLV ZLOO UHTXLUH QHZ ZDBV RI WKLQNLQJ DERXW WKH ZRUOG DV ZHOO DV QHZ WHFKQRORJLHV WR PDQLSXODWH LW. W, WRJHWKHU ZLWK O DQG WKH BRXQJ H ZLOO, L KRSH, EULQJ D QHZ SHUVSHFWLYH, DQG KHOS WR NHHS RXU OLWWOH FRQVSLUDFB DOLYH IRU DQRWKHU JHQHUDWLRQ. RXU DGYHQWXUHV VR IDU KDYH, RI QHFHVVLWB, EHHQ OLPLWHG LQ VFRSH, WKRXJK RXU DFTXLVLWLRQ RI EDEEDJHV SODQV DQG WKH VXSSUHVVLRQ RI KLV DQDOBWLF HQJLQH PXVW FRXQW DV D KLJKOLJKW. LI ZH DUH WR VXFFHHG RQ WKH JUDQG VFDOH WKDW ZH ERWK WKLQN LV QHFHVVDUB, WKHQ LW LV WLPH IRU XV WR IRUPDOLVH RXU DUUDQJHPHQWV DQG WR HVWDEOLVK D KHDGTXDUWHUV IRU RXU RSHUDWLRQV.L KDYH JLYHQ WKLV VRPH WKRXJKW DQG KDYH DQ LGHD WKDW L KRSH ZLOO SOHDVH BRX. ZH VKRXOG EXLOG D OLJKWKRXVH LQ ORQGRQ! L FDQ LPPHGLDWHOB VHH BRXU REMHFWLRQ. ORQGRQ KDV QR URFNB VKRUHV, DQG VR QR QHHG RI RQH, EXW BRXU HASHULPHQWV ZLWK ODQWHUQV JLYH XV WKH LGHDO HAFXVH WR EXLOG RQH DV D SODFH WR WHVW WKHP.WKH RSSRUWXQLWLHV WKLV ZLOO DIIRUG DUH PDQB WKH GHOLYHUB RI ODUJH FUDWHV RI HTXLSPHQW ZLOO JR XQQRWLFHG, FRQVLGHUHG DV SDUW RI WKH QDWXUDO EXVLQHVV RI WKH SODFH; LWV ORFDWLRQ RQ D EXVB ZKDUI ZRXOG GLVJXLVH WKH QHFHVVDUB FRPLQJV DQG JRLQJV RI RXU FR-FRQVSLUDWRUV; WKH ZDWHUZDB ZLOO SURYLGH XV ZLWK UHDGB WUDQVSRUWDWLRQ ERWK LQODQG YLD WKH FDQDOV DQG WR WKH GRFNV DW WLOEXUB IRU RXU LQWHUQDWLRQDO YHQWXUHV. QRW OHDVW, WKH HAWUDRUGLQDUB SRZHU QHHGHG IRU RXU GHYLFHV ZLOO EH PLVWDNHQ IRU WKH HQHUJB UHTXLUHG WR UXQ BRXU SXEOLF HASHULPHQWV.L KDYH OLWWOH HASHUWLVH LQ WKH GHVLJQ RU HQJLQHHULQJ RI VXFK VWUXFWXUHV, EXW L LPDJLQH WKDW WKHB UHTXLUH VXEVWDQWLDO IRRWLQJV. WKH GHYHORSPHQW RI WKHVH ZLOO SURYLGH WKH FRYHU ZH QHHG WR FRQVWUXFW RXU VHFUHW KHDGTXDUWHUV XQGHU WKH PRUH SXEOLF IDFH RI WKH OLJKWKRXVH LWVHOI DQG LWV DQFLOODUB EXLOGLQJV.LW PDB EH WKDW L KDYH PLVVHG VRPHWKLQJ LPSRUWDQW LQ PB FRQVLGHUDWLRQV, LQ ZKLFK FDVH SOHDVH GR SRLQW WKDW RXW, EXW LI ZH DUH WR SDVV RQ RXU GLVFRYHULHV, DPELWLRQV DQG SODQV WR WKH QHAW JHQHUDWLRQ ZH ZLOO QHHG WR JLYH WKHP D PRUH SHUPDQHQW KRPH, VR L KRSH ZH FDQ DJUHH WRJHWKHU RQ WKH EHVW ZDB WR SURFHHG.BRXUV, FK"
letter_map = {'A': "A",'B': "B",'C': "C",'D': "D",'E': "E",'F': "F",'G': "G",'H': "H",'I': "I",'J':"J",'K': "K",'L': "L",'M': "M",'N': "N",'O': "O",'P': "P",'Q': "Q",'R': "R",'S': "S",'T': "T",'U': "U",'V': "V",'W': "W",'X': "X",'Y': "Y",'Z' :"Z"}
modular_inv = {1:1, 3:9, 5:21, 7:15, 9:3, 11:19, 15:7, 17:23, 19:11, 21:5, 23:17, 25:25}

def freq_analysis(text):
    dic = {}
    for i in text:
        if dic.get(i):
            dic[i] += 1
        else:
            dic[i] = 1
    if dic.get(" "):
        del dic[" "]
    for i in dic:
        dic[i] /= len(text)* 0.01
    dic = {k: v for k, v in sorted(dic.items(), key=lambda item: item[1], reverse=True)}
    plt.bar(range(len(dic)),
    list(dic.values()),
    tick_label=list(dic.keys()))
    
    #Etaoin shrdlu
    iterator = iter(dic)
    letter_replace("e", next(iterator))
    letter_replace("t", next(iterator))
    letter_replace("a", next(iterator))
    text_replace()

def letter_replace(letter, replacer):
    letter_map[letter.upper()] = replacer.lower()

def text_replace():
    print(letter_map)
    new_text = ""
    for i in text:
        if i == " ":
            new_text += " "
        else:
            new_text += letter_map[i]
    print(new_text)

def affine():
    print()

#freq_analysis(text)
#plt.show()

text = "FASSB GAMRA CKGTP INUMO TUOVU FILAT UUYOY IIKTG NUFIX AWLUU SBGNE UOWNP ACKTO MIOVU FIMBT UISBT WSSOW NHGNE UFILG EFUFO WTICO NTPGS ACBCS IYANH GUFGN KGMAH ITOMI PSOES ITTYF GLIGY ATAYA BUFIU SAGNI ITUAC KLIHU FILIU UISVS OMARC ANHUF IBHGH AESIA UJORU FIBAS ITFAP GNEWP YILLG UFGNK YIYGL LRIEL AHOVU FIGSF ILPAT UFGTC ATIPS OESIT TITUF ILGRS ASGAN AUUFI XAWLU YATXI SBFIL PVWLA NHYFI NGUOL HFISY FAUGY ATLOO KGNEV OSTFI POGNU IHMIU OANAS CFGXI OVXGC UOSGA NPAPI STCON CISNG NETCG INUGT UTINE GNIIS TANHT OCGAL SIVOS MISTU FAUFA HSICO SHIHI ASLBR ACKES OWNHG NXITU GEAUG ONTGN UOPIO PLIOV GNUIS ITUGT ABPIO PLIRW UGHGH NOUGC IUFAU UFISI YATAF IAXBR GATUO GNXIT UGEAU GNEYO MINRA CKUFI NGYAT TWSPS GTIHA UVGST UGFAH ATTWM IHUFA UUFIB YOWLH FAXIR IINLA SEILB GENOS IHRWU GTWPP OTIUF ITISI MASKA RLIYO MINMA HIUFI GSPSI TINCI KNOYN ANHPI SFAPT UFIIT UARLG TFMIN UVILU UFSIA UINIH GNMOT UCATI TUFIS IASIN OTUAN HASHT ICWSG UBVGL ITVOS UFITI YOMIN RWUYF ISIUF ISIYI SIUFI BYISI AURIT UUFGN UFISI ALLBG NUISI TUGNE MAUIS GALYA TGNUF IFGHH INASC FGXIY FISIG VOWNH SIPOS UTANH PAPIS TAROW ULOXI LACIN GEFUG NEALI ANHAR CATIT UARLG TFMIN UVGEW SITUF IMTIL XITUF IBTII MUOFA XIRII NGENO SIHRB UFITI CSIUT ISXGC IANHC LIASL BNOUC ONTGH ISIHA TICWS GUBUF SIAUR WUOWS ROTTV OSIRI ASTHG HCASS BOWUG NXITU GEAUG ONTGN UOUFI GSACU GXGUG ITANH UFISI ASICL IASTG ENTUF AUUFI BMABF AXIYO SKIHU OEIUF ISORX GOWTL BUFIV ACUUF AUUFI BYISI MAKGN ETWCF ANGMP ACUON TOCGI UBYAT INOWE FUOMA KITOM IPIOP LINIS XOWTA VUISA LLGUY ATAUG MIOVE SIAUC FANEI ANHCO NCISN TAROW USIXO LWUGO NYISI XISBS IALON IOVUF INOUI TONVG LITWE EITUT UFAUU FIESO YGNEC AMPAG ENVOS YOMIN TTWVV SAEIA NHTOC GALAC UGXGT MMGEF UFAXI RIINU FITUA SUOVA NGNTW SSICU GONAN HGUNA MIHTI XISAL OVOWS PSOUA EONGT UTRWU GUHGH NUTAB FOYUF IBMGE FUFAX IGNUI NHIHU OUSGE EISUF IWPSG TGNEY FAUYI FAXIT IINTO VASGT UFAUY FAUIX ISUFI LGEFU FOWTI CONTP GSACB YISIW PUOUF IBYIN UUOIZ USAOS HGNAS BLINE UFTUO KIIPG UTICS IUANH UFIVA CUUFA UYIAS IONLB NOYWN COXIS GNEGU TWEEI TUTUF AUGUY ATMWC FTWRU LISUF ANAPL ANNIH WPSGT GNEGA MTUGL LTUSW EELGN EYGUF UFIGH IAUFA UPIOP LIYFO YISIP ASUOV UFIRG SUFOV ROTTC OWLHF AXIRI INACU GNETI CSIUL BAEAG NTUWT RWUUF AUGTC ISUAG NLBGM PLGIH RBTOM IOVUF IVGLI TYIFA XICSA CKIHA NHUFI AUUAC FIHHO CWMIN UFATA HHIHU OMBYO SSGIT GUYAT YSGUU INGNU FIAVU ISMAU FOVUF IFGNH INRWS EHGTA TUISR BTOMI ONIGU FGNKB OWKNI YYILL TFIFA HAVAN UATUG CSICO SHYOS KGNEH IIPWN HISCO XISAN HSIPO SUGNE RACKU OYITU ISNGN UILLG EINCI AEINC GITRW UUFIU FGNEU FAUCA WEFUM BIBIY ATUFA UFISI TFIWT IHUFI COHIN AMIAW EWTUA GHONU KNOYG VBOWA LSIAH BTPOU UIHGU RWUUF ILIUU ISGNE ASOWN HUFII HEIOV UFILG EFUFO WTITU AMPSI AHTAH AAHHH AAAHA AAHAH ANHTW RTUGU WUGNE UFIAA NHHVO SHOUA NHHAT FTPIL LTOWU FISCO HINAM IGUFO WEFUA UVGST UUFAU GMGEF URISI AHGNE UOOMW CFGNU OGUUF ILIUU ISGNF ISVGL ITIIM TNIXI SUOFA XIRII NRSOK INTOM IONIY SOUIH OWRLI INCSB PUIHO NUFII NXILO PIANH GEWIT TUFAU YATIN OWEFU OHGTT WAHIU FIAEI NCGIT VSOMT PINHG NEMWC FUGMI ONGUY GUFFG NHTGE FUGUG TPSIU UBORX GOWTU FAUAC UWALL BGUFA TJWTU RIINI NCSBP UIHON CIANH UFINI NCOHI HATMO STICO HIWTG NEUFI TAMIC ONXIN UGONA IQWAL THOUH IQWAL THATF ONCIU FAUFA HRIIN WNUAN ELIHG VOWNH GUPSI UUBIA TBUOR SIAKA NHGAM XISBY OSSGI HAROW UYFAU GVOWN HGUFG NKBOW NIIHU OUAKI ALOOK JOHGI"

text = text.replace(" ", "")
def virgenere():
    strings = []
    key_length = 4
    short = ""
    for i in range(int(len(text)/4)):
        short = text[4*i: 4*i+key_length]
        strings.append(short)
    strings.append(text[len(text)-len(text)%key_length:len(text)])
   
    for i in range(len(strings)):
        strings
   
print(virgenere())
